name: Emily Evenden, HTML extrodinaire
#markdown: kramdown
#permalink: /blog/:year/:month/:day/:title

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  
  social_links:
    linkedin: Emily Evenden
    github:  eevenden

theme: minima
